meta_product_name: "Product Name"
meta_title: "MindNote - The right way to practice"
meta_description: "Tracks all your music and tells you the best songs to practice"
meta_image: "og-image.png"
twitter_account: "@mindnotepro"
